/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:53aa09bd-0843-4b74-a234-52662fea16bb",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_TTbAlniBT",
    "aws_user_pools_web_client_id": "313jvebku92lealim00t0n9qla",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "deliveryAPI",
            "endpoint": "https://nadlmoezsb.execute-api.eu-west-1.amazonaws.com/staging",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "delivery-proof-s3-aws-hackaton102046-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
